config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :question_types
  resources :question_type2s
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/question_types_controller.rb
class QuestionTypesController < ApplicationController
  before_action :set_question_type, only: [:show, :edit, :update, :destroy]

  # GET /question_types
  # GET /question_types.json
  def index
    @question_types = QuestionType.all
  end

  # GET /question_types/1
  # GET /question_types/1.json
  def show
  end

  # GET /question_types/new
  def new
    @question_type = QuestionType.new
  end

  # GET /question_types/1/edit
  def edit
  end

  # POST /question_types
  # POST /question_types.json
  def create
    @question_type = QuestionType.new(question_type_params)

    respond_to do |format|
      if @question_type.save
        format.html { redirect_to @question_type, notice: 'Question type was successfully created.' }
        format.json { render :show, status: :created, location: @question_type }
      else
        format.html { render :new }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_types/1
  # PATCH/PUT /question_types/1.json
  def update
    respond_to do |format|
      if @question_type.update(question_type_params)
        format.html { redirect_to @question_type, notice: 'Question type was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_type }
      else
        format.html { render :edit }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_types/1
  # DELETE /question_types/1.json
  def destroy
    @question_type.destroy
    respond_to do |format|
      format.html { redirect_to question_types_url, notice: 'Question type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_type
      @question_type = QuestionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_type_params
      params.require(:question_type).permit(:name, :description, :color, :sn_active_qt)
    end
end

app/helpers/question_types_helper.rb
module QuestionTypesHelper
end

app/views/question_types/_form.html.erb
<%= form_with(model: question_type, local: true) do |form| %>
  <% if question_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_type.errors.count, "error") %> prohibited this question_type from being saved:</h2>

      <ul>
      <% question_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :sn_active_qt %>
    <%= form.check_box :sn_active_qt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/question_types/edit.html.erb
<h1>Editing Question Type</h1>

<%= render 'form', question_type: @question_type %>

<%= link_to 'Show', @question_type %> |
<%= link_to 'Back', question_types_path %>

app/views/question_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Color</th>
      <th>Sn active qt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_types.each do |question_type| %>
      <tr>
        <td><%= question_type.name %></td>
        <td><%= question_type.description %></td>
        <td><%= question_type.color %></td>
        <td><%= question_type.sn_active_qt %></td>
        <td><%= link_to 'Show', question_type %></td>
        <td><%= link_to 'Edit', edit_question_type_path(question_type) %></td>
        <td><%= link_to 'Destroy', question_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question Type', new_question_type_path %>

app/views/question_types/new.html.erb
<h1>New Question Type</h1>

<%= render 'form', question_type: @question_type %>

<%= link_to 'Back', question_types_path %>

app/views/question_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @question_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @question_type.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @question_type.color %>
</p>

<p>
  <strong>Sn active qt:</strong>
  <%= @question_type.sn_active_qt %>
</p>

<%= link_to 'Edit', edit_question_type_path(@question_type) %> |
<%= link_to 'Back', question_types_path %>